[changelog]
header = "# Changelog\n\n"
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_preprocessors = [
  { pattern = "^feat", replace = "âœ¨ feat" },
  { pattern = "^fix", replace = "ğŸ› fix" },
  { pattern = "^docs", replace = "ğŸ“š docs" },
  { pattern = "^refactor", replace = "â™»ï¸ refactor" },
  { pattern = "^perf", replace = "âš¡ perf" },
  { pattern = "^test", replace = "âœ… test" },
  { pattern = "^chore", replace = "ğŸ”§ chore" }
]

commit_parsers = [
  { message = "^âœ¨ feat", group = "ğŸš€ Features" },
  { message = "^ğŸ› fix", group = "ğŸ› Bug Fixes" },
  { message = "^ğŸ“š docs", group = "ğŸ“š Documentation" },
  { message = "^â™»ï¸ refactor", group = "â™»ï¸ Refactor" },
  { message = "^âš¡ perf", group = "âš¡ Performance" },
  { message = "^âœ… test", group = "âœ… Tests" },
  { message = "^ğŸ”§ chore", group = "ğŸ”§ Chore" }
]
